=== inf24tig36/inf24tig36/Valida.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Ementa">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Sopa" type="DiaSemanaType"/>
        <xs:element name="PratoDeCarne" type="DiaSemanaType"/>
        <xs:element name="PratoDePeixe" type="DiaSemanaType"/>
        <xs:element name="Fruta" type="DiaSemanaType"/>
        <xs:element name="Sobremesa" type="DiaSemanaType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="DiaSemanaType">
    <xs:sequence>
      <xs:element name="Segunda" type="xs:string"/>
      <xs:element name="Terca" type="xs:string"/>
      <xs:element name="Quarta" type="xs:string"/>
      <xs:element name="Quinta" type="xs:string"/>
      <xs:element name="Sexta" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== inf24tig36/inf24tig36/ementa.xml
<?xml version="1.0" encoding="UTF-8"?>
<Ementa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Valida.xsd">
  <Sopa>
    <Segunda>Canja</Segunda>
    <Terca>Sopa de legumes</Terca>
    <Quarta>Sopa á Lavrador</Quarta>
    <Quinta>Ramen</Quinta>
    <Sexta>Sopa de Letras</Sexta>
  </Sopa>
  <PratoDeCarne>
    <Segunda>Frango</Segunda>
    <Terca>Bife</Terca>
    <Quarta>Sopa á Lavrador</Quarta>
    <Quinta>Ramen</Quinta>
    <Sexta>Sopa de Letras</Sexta>
  </PratoDeCarne>
  <PratoDePeixe>
    <Segunda>Frango</Segunda>
    <Terca>Bife</Terca>
    <Quarta>Sopa á Lavrador</Quarta>
    <Quinta>Ramen</Quinta>
    <Sexta>Sopa de Letras</Sexta>
  </PratoDePeixe>
  <Fruta>
    <Segunda>Frango</Segunda>
    <Terca>Bife</Terca>
    <Quarta>Sopa á Lavrador</Quarta>
    <Quinta>Ramen</Quinta>
    <Sexta>Sopa de Letras</Sexta>
  </Fruta>
  <Sobremesa>
    <Segunda>Frango</Segunda>
    <Terca>Bife</Terca>
    <Quarta>Sopa á Lavrador</Quarta>
    <Quinta>Ramen</Quinta>
    <Sexta>Sopa de Letras</Sexta>
  </Sobremesa>
</Ementa>
